Fifo depth opt vitis
fastmachinelearning/hls4ml pull request #1037
Opened 2024-07-18 12:59 UTC by steltze

_FIFO depth optimization_ optimizer for the Vitis backend using the built-in cosim FIFO profiling feature of Vitis HLS
- Inserted the new optimizer to the Vitis backend flows
- Implemented the optimizer. The steps are similar to the Vivado optimizer, only the profiling and FIFO depth parsing parts change
- Updated the Vitis Write to overwrite the `project.tcl` file with Vitis attributes
- Updated the `build_prj.tcl` file to skip the *add_vcd_instructions_tcl* function in the case of Vitis backend

> :memo: Please include a summary of the change.
>
> * Please also include relevant motivation and context.
> * List any dependencies that are required for this change.

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [x] Documentation update
- [x] New feature (non-breaking change which adds functionality)

## Tests

- Used Vitis HLS 2023.2
- Dummy dense model example. However, optimized depths are the same as the initial ones set by hls4ml

```python
import hls4ml
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
model = Sequential()
model.add(Dense(64, input_shape=(16,), name='fc1', activation='relu')
model.add(Dense(64, input_shape=(16,), name='fc1', activation='relu'))
model.add(Dense(32, name='fc2', activation='relu'))
model.add(Dense(32, name='fc3', activation='relu'))
model.add(Dense(5, name='fc3', activation='softmax'))
model.add(Dense(5, name='fc4', activation='softmax'))

config = hls4ml.utils.config_from_keras_model(model, default_precision='ap_fixed<8, 4>')
config['Flows'] = ['vitis:fifo_depth_optimization']
hls4ml.model.optimizer.get_optimizer('vitis:fifo_depth_optimization').configure(profiling_fifo_depth=200_000)

output_dir = 'hls4mlprj_fifo_depth_opt_vitis'
hls_model = hls4ml.converters.convert_from_keras_model(model,
                                                       io_type='io_stream',
                                                       hls_config=config,
                                                       output_dir=output_dir,
                                                       part='xc7z020clg400-1',
                                                       backend='Vitis')

hls_model.build(reset=False, csim=False, synth=True, cosim=True)
hls4ml.report.read_vivado_report(output_dir)
```
- Tested the model above with Vivado to ensure nothing broke
- 10k param U-Net model. After running cosim with the optimized depths, no deadlocks are detected by Vitis
- [ ] Added unit test to the hls4ml pytests

> :memo: Please describe the tests that you ran to verify your changes.
>
> * Provide instructions so we can reproduce.
> * Please also list any relevant details for your test configuration.

**Test Configuration**:

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/fastmachinelearning/hls4ml/blob/main/CONTRIBUTING.md).
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have installed and run `pre-commit` on the files I edited or added.
- [ ] I have added tests that prove my fix is effective or that my feature works.

2024-07-25 10:02 UTC, steltze commented
hey @vloncar @jmitrevs do you think a unit test is required? To avoid delaying the CI pipeline, I could add a dummy model that verifies synthesis and that the flow is executed. Otherwise, I can add a complete unit test that also checks the FIFO depth results

2024-07-25 12:57 UTC, vloncar commented
I think it would be good to have a full test, but until we improve the synthesis testing pipeline, maybe mark it with `@pytest.mark.skip(reason='Skipping synthesis tests for now')`. This way we could run it locally when we review your code and it won't cause issues in the CI.

2024-08-01 08:49 UTC, steltze commented
To the reviewers: when we agree on how we want to test this, I can open an issue to also include the Vivado/VivadoAccelerator FIFO optimization in the tests, as a future PR, as some changes in the initial implementation of those backends will be needed

2024-09-23 08:12 UTC, steltze commented
After discussing, some more todos:
- [ ] Update the hls4ml documentation by including an example of this feature with the Vitis backend
- [ ] Include a UNet model on the pytest

2025-01-28 15:37 UTC, nghielme reviewed
In general it looks good to me 👍

2025-01-28 15:37 UTC, nghielme commented on hls4ml/backends/vitis/passes/fifo_depth_optimization.py
> +    # they will be profiled. Alternatively, "config_dataflow -override_user_fifo_depth profiling_fifo_depth" can be
Is there any particular reason why you didn't opt for the modification of `build_prj.tcl`?

2025-01-28 15:37 UTC, nghielme commented on hls4ml/backends/vitis/passes/fifo_depth_optimization.py
> +                newline += indent + indent + "const unsigned BATCH_SIZE = 2;\n"
To my understanding `BATCH_SIZE` is not appropriate here, you are calling `N` times the same function for profiling purposes. `PROFILING_ITERATIONS`?

2025-01-28 15:37 UTC, nghielme commented on hls4ml/backends/vitis/passes/fifo_depth_optimization.py
> +        if not isinstance(profiling_fifo_depth, int) or profiling_fifo_depth < 0:
Is `depth=0` acceptable?

2025-01-28 15:37 UTC, nghielme commented on test/pytest/test_optimization/test_fifo_depth.py
> +    dl_file = str(example_model_path / "onnx/branched_model_ch_last.onnx")
I think this one is a model with a single branch, is not a UNet model. `tiny_unet_ch_last.onnx` should be the UNet one

2025-02-10 10:42 UTC, steltze commented on hls4ml/backends/vitis/passes/fifo_depth_optimization.py
> +    # they will be profiled. Alternatively, "config_dataflow -override_user_fifo_depth profiling_fifo_depth" can be
the outcome is the same so I just implemented the easiest option, rather than changing the tcl script

2025-02-10 10:47 UTC, steltze commented on test/pytest/test_optimization/test_fifo_depth.py
> +    dl_file = str(example_model_path / "onnx/branched_model_ch_last.onnx")
I chose this one since it's smaller and the test will run for a shorter period

2025-02-10 11:20 UTC, nghielme commented on test/pytest/test_optimization/test_fifo_depth.py
> +    dl_file = str(example_model_path / "onnx/branched_model_ch_last.onnx")
Ok, makes sense. Just modify the comment for consistency then 👍

2025-02-10 11:47 UTC, steltze commented on test/pytest/test_optimization/test_fifo_depth.py
> +    dl_file = str(example_model_path / "onnx/branched_model_ch_last.onnx")
done. fixed all comments

2025-02-21 16:00 UTC, jmitrevs requested changes

2025-02-21 16:00 UTC, jmitrevs commented on hls4ml/writer/vitis_writer.py
> +        f.write('set clock_uncertainty {}\n'.format(model.config.get_config_value('ClockUncertainty', '12.5%')))
Why do we put a clock uncertainty of 12.5% here?  Also in general, would it be better to have a project.tcl template that we edit?

2025-03-03 16:22 UTC, steltze commented on hls4ml/writer/vitis_writer.py
> +        f.write('set clock_uncertainty {}\n'.format(model.config.get_config_value('ClockUncertainty', '12.5%')))
@jmitrevs this should be the default one set at also at the vivado backend from the [writer](https://github.com/fastmachinelearning/hls4ml/blob/898d53d0d4438b0e8abb7a6aebb4bf7e6a0a8835/hls4ml/writer/vivado_writer.py#L717)

2025-03-03 17:11 UTC, nghielme commented on hls4ml/writer/vitis_writer.py
> +        f.write('set clock_uncertainty {}\n'.format(model.config.get_config_value('ClockUncertainty', '12.5%')))
Hi @vloncar ,
thanks for testing. I am also testing in parallel it and I noticed that `project.tcl` is generated assigning the wrong name to `project_name` variable (`myproject` vs `myproject_axi`). Have you noticed the same as well and added in your changes?

2025-03-03 17:13 UTC, nghielme commented on hls4ml/writer/vitis_writer.py
> +        f.write('set clock_uncertainty {}\n'.format(model.config.get_config_value('ClockUncertainty', '12.5%')))
as I wrote somewhere else in this PR, I think it would be beneficial for to have a test in which a simple model is created and synthetised with Vivado (so that all the Vivado synthesis errors can be spotted as well)

2025-03-03 18:33 UTC, vloncar approved these changes

2025-03-03 18:40 UTC, vloncar commented
This looks good and ready to be merged. One change I made (which I think is long overdue) is to ensure multiple iterations of the top function are called when user doesn't provide any input. All co-simulation results with io_stream are invalid when only one input is passed, not just the FIFO depth but latency and II. This PR originally suggested to call the top function twice, but in the past I have observed that for some ResNet blocks I needed to run co-sim 4 times (3 times to see the buffers fill up, 4th time to be sure they stopped increasing). I placed 5 to be sure. For large models this may take a lot of time, so we shouldn't go to much larger numbers as a default.

2025-03-03 23:44 UTC, merged