Initial values for the hidden/cell state for LSTM and GRU models in Pytorch
fastmachinelearning/hls4ml pull request #1120
Opened 2024-11-11 17:03 UTC by JanFSchulte

This PR addresses https://github.com/fastmachinelearning/hls4ml/issues/1074 and implements the passing of initial values for the hidden and cell states in GRU and LSTM models, which is supported in pytorch. This first version implements this only for the pytorch parser, but it should be able to be extended it for keras and other parsers. 

Note that this currently only works in `io_parallel`. In `io_stream` I was having some conceptual issues and was unsure if I should treat these initial states are streamed inputs or not. Might be good enough for now and I can revisit `io_stream` if there are any suggestions how to tackle that. 

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Tests

Tested in both standalone scripts and also the pytests to ensure that model parsing and evaluation work with and without passing these optional tensors. 

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/fastmachinelearning/hls4ml/blob/main/CONTRIBUTING.md).
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have installed and run `pre-commit` on the files I edited or added.
- [x] I have added tests that prove my fix is effective or that my feature works.

2025-01-18 02:24 UTC, jmitrevs requested changes

2025-01-18 02:24 UTC, jmitrevs commented on hls4ml/templates/quartus/firmware/nnet_utils/nnet_recurrent.h
> +    res_T hidden_state[CONFIG_T::n_out][CONFIG_T::n_timesteps + 1] hls_register;
Shouldn't `hidden_state` be of type `data2_T` and `cell_state` of type `data3_T`?

2025-02-07 17:19 UTC, jmitrevs commented
We need to fix the datatypes for oneAPI before we merge

2025-02-12 14:26 UTC, JanFSchulte commented
pre-commit.ci autofix

2025-02-14 21:26 UTC, jmitrevs approved these changes

2025-02-15 21:21 UTC, vloncar commented on hls4ml/converters/keras/recurrent.py
> +    layer['pass_initial_states'] = False
Not quite, right? We find out from number of inputs. Also, would be good to add this as an expected attribute to the RNN layers in IR

2025-02-15 21:22 UTC, vloncar commented on hls4ml/converters/pytorch_to_hls.py
> +                for i in node.args:
can we have more descriptive names of variables `i` and `y`

2025-02-15 21:25 UTC, vloncar commented on hls4ml/templates/oneapi/firmware/nnet_utils/nnet_recurrent.h
> +struct simpleRNN_pytorch_config {
A minor annoyance is that this breaks naming convention, I was expecting `simple_rnn_...`

2025-02-15 21:27 UTC, vloncar commented on hls4ml/templates/vivado/nnet_utils/nnet_recurrent.h
> +template <class data_T, class data2_T, class data3_T, class res_T, typename CONFIG_T>
Any more descriptive names than `data2_T` and `data3_T`?

2025-02-15 21:28 UTC, vloncar reviewed
Looks good, I left some comments on cosmetics

2025-02-15 21:29 UTC, jmitrevs commented on hls4ml/templates/vivado/nnet_utils/nnet_recurrent.h
> +template <class data_T, class data2_T, class data3_T, class res_T, typename CONFIG_T>
I tried to put more descriptive names in the oneAPI version. Maybe we can go more in that direction for the other backends (and potentially standardize).

2025-02-15 21:41 UTC, jmitrevs commented on hls4ml/templates/oneapi/firmware/nnet_utils/nnet_recurrent.h
> +struct simpleRNN_pytorch_config {
Actually, this is never used (and similarly also not for quartus). It seems like the `simpleRNN_config` is used for all cases. Of course that one also violates the naming convention.

2025-02-15 21:57 UTC, jmitrevs commented on hls4ml/templates/oneapi/firmware/nnet_utils/nnet_recurrent.h
> +struct simpleRNN_pytorch_config {
My suggestion is that we remove `simpleRNN_pytorch_config`  and rename `simpleRNN_config`, though we could keep the two if we really wanted to. That would complicate the templates a touch for no real gain. (I truthfully was never much of a fan of the base config templates that get overriden.)

2025-02-18 16:52 UTC, jmitrevs commented on hls4ml/templates/oneapi/firmware/nnet_utils/nnet_recurrent.h
> +struct simpleRNN_pytorch_config {
https://github.com/JanFSchulte/hls4ml/pull/9 does the simple approach to rename `simpleRNN_config` as `simple_rnn_config` and remove `simpleRNN_pytorch_config` altogether, if you agree with that approach.

2025-02-24 15:05 UTC, JanFSchulte commented on hls4ml/converters/pytorch_to_hls.py
> +                for i in node.args:
Done.

2025-02-25 00:29 UTC, vloncar approved these changes

2025-02-25 00:29 UTC, merged