oneAPI 2025.0 include changes
fastmachinelearning/hls4ml pull request #1149
Opened 2024-12-13 09:46 UTC by laurilaatu

# Removing include for 2025.0

## Type of change

oneAPI 2025.0 removes `interfaces.hpp` and the relevant functions are available from `fpga_extensions.hpp`

- [x] Bug fix (non-breaking change that fixes an issue)

## Checklist

- [x] My changes generate no new warnings.
- [x] I have installed and run `pre-commit` on the files I edited or added.

2024-12-13 21:03 UTC, jmitrevs commented
Changing this to draft till we update our test environment.

2025-01-10 17:03 UTC, bo3z requested changes
We can merge this but I would like to confirm this indeed works with oneAPI < 2025.0. If not, there should be an #ifdef checking for the version.

2025-01-10 19:06 UTC, JanFSchulte commented
Pytests have passed, so I guess this change is save an can be merged now?

2025-01-10 19:19 UTC, jmitrevs commented
The pytest wouldn't catch the failure since it's in the _test file. Lauri will add ifdefs, he said.

2025-01-10 19:22 UTC, JanFSchulte commented
Ah, I misunderstood. Great news about ifdefs.

2025-01-14 16:03 UTC, merged