added check for conv implementation
fastmachinelearning/hls4ml pull request #1155
Opened 2024-12-17 18:11 UTC by jicampos

A# Description

> :memo: Please include a summary of the change.
> 
> * Please also include relevant motivation and context.
> * List any dependencies that are required for this change.

## Type of change
This change adds a check in the Vivado backend to skip instruction calculations for CONV1D and CONV2D when using linebuffer implementations. Since linebuffers do not require calculating **instructions**, **min_height**, or **min_width**, performing these calculations is redundant.

Note: Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Documentation update
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] A new research paper code implementation
- [ ] Other (Specify)

## Tests

> :memo: Please describe the tests that you ran to verify your changes.
>
> * Provide instructions so we can reproduce.
> * Please also list any relevant details for your test configuration.

**Test Configuration**:

## Checklist

- [ ] I have read the [guidelines for contributing](https://github.com/fastmachinelearning/hls4ml/blob/main/CONTRIBUTING.md).
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have installed and run `pre-commit` on the files I edited or added.
- [ ] I have added tests that prove my fix is effective or that my feature works.

2024-12-17 18:18 UTC, jmitrevs commented
I will just add that the reason for this change was because in some cases the instructions became huge and made compilation more difficult, even though they were then unused.

2024-12-17 19:05 UTC, jmitrevs commented
It does seem to cause some test failures that should be investigated.

2024-12-17 19:31 UTC, jmitrevs commented on hls4ml/backends/vivado/passes/conv_stream.py
> +        if node.model.config.get_config_value('IOType') == 'io_stream' and node.get_attr('conv_implementation') == 'Encoded':
One should maybe make this check case-insensitive.

2024-12-17 20:41 UTC, jmitrevs commented
I think "Instructions" implies encoded to me, but maybe not to everyone. But I do like the idea of moving this to the match. There may need to be some changes in the parameter creation to make sure unused variables aren't implicitly required, but that should be fairly easy to fix.

2024-12-18 18:58 UTC, jicampos commented
> Would it make sense to add this check in the match() method rather than the transform() method? That way the optimizer will never even be executed. Also, since this only applies to encoded implementation, should we rename this optimizer to reflect that?


We would still need to run the optimizer to add dummy weights in the case of LineBuffer implementations but we can skip generating instructions with the added condition in the if statement.

2024-12-18 20:47 UTC, jmitrevs commented
I think the suggestion from @bo3z is the better approach. Can we change it so that the check is on the match? There may be some downstream minor fixes needed with that approach, though, mainly allowing for undefined instructions and min widths/heights.

2024-12-18 21:41 UTC, jicampos commented
> I think the suggestion from @bo3z is the better approach. Can we change it so that the check is on the match? There may be some downstream minor fixes needed with that approach, though, mainly allowing for undefined instructions and min widths/heights.

I've updated the optimizer match() to check the IOType and implementation. The LineBuffer default values are now added to Conv2DConfigTemplate and Conv1DConfigTemplate.

2025-01-09 22:51 UTC, jmitrevs requested changes

2025-01-09 22:51 UTC, jmitrevs commented on hls4ml/backends/vivado/passes/convolution_templates.py
> +        if node.get_attr('implementation').casefold() == 'linebuffer':
Would this fail if for some reason I set the implementation to encoded but then used io_parallel? I know it's not meaningful, but I wonder if it would be best to just set them if not set regardless of the implementation.

2025-01-09 22:51 UTC, jmitrevs commented on hls4ml/backends/vivado/passes/convolution_templates.py
> +        if node.get_attr('implementation').casefold() == 'linebuffer':
Same issue here as above

2025-01-14 22:41 UTC, jicampos commented on hls4ml/backends/vivado/passes/convolution_templates.py
> +        if node.get_attr('implementation').casefold() == 'linebuffer':
After updating the tests to include this case, it fails since the optimizer pass now checks for io_stream. The latest commit (a3ec21022042f627fe6ddaccebae04db0a19cf3d) resolves this issue. The test case has also been added in pytest.

2025-01-17 00:21 UTC, jmitrevs approved these changes

2025-01-17 00:22 UTC, jmitrevs commented
We should wait to make sure all the pytests pass first before merging. (Maybe got ahead of myself approving.)

2025-01-17 17:10 UTC, jicampos commented
> We should wait to make sure all the pytests pass first before merging. (Maybe got ahead of myself approving.)

It seems the tests are failing because of a connection issue in the qkeras tests, and is unrelated to the PR. 

Before rerunning any tests, should we update the catapult backend with the same changes?

2025-01-17 17:17 UTC, jmitrevs commented
I agree that the test failure is unrelated. If you can add the same to Catpult, that would be great. (No other backend has encoded.)

2025-01-17 18:22 UTC, jicampos commented
> I agree that the test failure is unrelated. If you can add the same to Catpult, that would be great. (No other backend has encoded.)

That sounds good, the catapult backend has been updated.

2025-01-17 20:12 UTC, jmitrevs requested changes

2025-01-17 20:12 UTC, jmitrevs commented on hls4ml/backends/catapult/passes/convolution_templates.py
> +        if (
Is it possible to just always set default values?

2025-01-17 20:12 UTC, jmitrevs commented on hls4ml/backends/catapult/passes/conv_stream.py
> +            and node.model.config.get_config_value('IOType').casefold() == 'io_stream'
We haven't used casefold in other places. People has suggested to use 'lower' for consistency with other parts of the code.

2025-01-18 01:44 UTC, jmitrevs requested changes

2025-01-18 01:44 UTC, jmitrevs commented on hls4ml/backends/catapult/passes/convolution_templates.py
> +        params.setdefault('min_width', node.get_attr('in_width'))
I think these can be replaced with just `params['min_witdth'] = node.get_attr('in_width')` and similar. Note that params is created on line 82, so `params['min_witdth']` is not set. The setdefaults has the same effect as `params['min_witdth'] = node.get_attr('in_width')`, so it's better to just use the more straightforward form.

2025-02-04 20:19 UTC, jmitrevs approved these changes

2025-02-04 20:20 UTC, merged