Support for 1D dot product
fastmachinelearning/hls4ml pull request #246
Opened 2020-11-20 19:53 UTC by DelonShen

I'm still not too familiar with everything in the code base but I think this should be alright for 1D dot products. Let me know what changes need to be made

2020-11-20 20:05 UTC, vloncar commented
Hi @DelonShen Thanks a lot for the PR. I'll look into it. Can you also provide an example model that demonstrates the correctness of the implementation?

2020-11-20 20:10 UTC, DelonShen commented
```
import numpy as np
from keras.models import Input, Model, load_model
import hls4ml
import keras

def build_dot():
    input_1 = Input(shape = (5,))
    output_1 = keras.layers.Dot(axes=1)([input_1,input_1])
    output = keras.layers.Add()([output_1,output_1])
    return Model(inputs = input_1, outputs = output)

inp = np.array([np.random.rand(5)])
model = build_dot()

y_mod = model.predict(inp)
print('MODEL OUTPUT', y_mod)
config = hls4ml.utils.config_from_keras_model(model, granularity='model')

hls_model = hls4ml.converters.convert_from_keras_model(model,
                                                       hls_config=config,
                                                       output_dir='test_dot')

hls_model.compile()
y_hls = hls_model.predict(inp)
print('HLS OUTPUT', y_hls)
```

2020-11-22 20:09 UTC, vloncar requested changes
Thanks a lot! Only minor changes to keep consistent with the rest of the style. Pay attention to the whitespace (no tabs and extra lines after new code) ;-)

2020-11-22 20:09 UTC, vloncar commented on hls4ml/model/hls_layers.py
> +
Remove this extra whitespace

2020-11-22 20:09 UTC, vloncar commented on hls4ml/templates/vivado/nnet_utils/nnet_merge.h
> +    static const unsigned n_elem = 10;
To be consistent with the other layers, can we name these `n_in` and `n_out`?

2020-11-22 20:09 UTC, vloncar commented on hls4ml/templates/vivado/nnet_utils/nnet_merge.h
> +};
We're missing a `reuse_factor` field here, since we are using multiplication in implementation.

2020-11-22 20:09 UTC, vloncar commented on hls4ml/templates/vivado/nnet_utils/nnet_merge.h
> +      res[0] += data1[ii] * data2[ii];
You should call `product` function here and store the result in intermediate array and accumulate the result later. Also, add limiter for the number of DSPs allocated. Look into `nnet_dense_latency.h` to see how to do those two things. Also, this function should be pipelined, so add a pragma before the loop.

2020-11-23 00:56 UTC, DelonShen commented
Hi, I think I've made the changes requested. Let me know if anythings wrong, I've never used pragma before and it's been a while since I've used templates.

2020-11-24 19:46 UTC, vloncar commented
@DelonShen Look into delonshen/hls4ml#1

Tested with this code:
```
import numpy as np
from tensorflow.keras.models import Model, load_model
import hls4ml
from tensorflow.keras.layers import Input, Dot, Add

def build_dot():
    input_1 = Input(shape = (100,))
    input_2 = Input(shape = (100,))
    output = Dot(axes=1)([input_1,input_2])
    return Model(inputs = [input_1,input_2], outputs = output)

model = build_dot()
config = hls4ml.utils.config_from_keras_model(model, granularity='model')
config['Model']['ReuseFactor'] = 5

hls_model = hls4ml.converters.convert_from_keras_model(model, hls_config=config, output_dir='test_dot')
hls_model.write()
hls_model.build(synth=True)
hls4ml.report.read_vivado_report('test_dot')
```

And the synthesis properly picks up `ReuseFactor`:
```
================================================================
== Utilization Estimates
================================================================
* Summary: 
+---------------------+---------+-------+---------+--------+-----+
|         Name        | BRAM_18K| DSP48E|    FF   |   LUT  | URAM|
+---------------------+---------+-------+---------+--------+-----+
|DSP                  |        -|      -|        -|       -|    -|
|Expression           |        -|      -|        0|       6|    -|
|FIFO                 |        -|      -|        -|       -|    -|
|Instance             |        -|     20|     3811|    2905|    -|
|Memory               |        -|      -|        -|       -|    -|
|Multiplexer          |        -|      -|        -|     123|    -|
|Register             |        -|      -|     3209|       -|    -|
+---------------------+---------+-------+---------+--------+-----+
|Total                |        0|     20|     7020|    3034|    0|
+---------------------+---------+-------+---------+--------+-----+
|Available SLR        |     2160|   2760|   663360|  331680|    0|
+---------------------+---------+-------+---------+--------+-----+
|Utilization SLR (%)  |        0|   ~0  |        1|   ~0   |  100|
+---------------------+---------+-------+---------+--------+-----+
|Available            |     4320|   5520|  1326720|  663360|    0|
+---------------------+---------+-------+---------+--------+-----+
|Utilization (%)      |        0|   ~0  |    ~0   |   ~0   |    0|
+---------------------+---------+-------+---------+--------+-----+
```

2020-11-27 21:43 UTC, vloncar approved these changes
Looks good!

2020-12-02 13:53 UTC, merged