Support doing Dense over n-dimensional (n>1) tensor with 1x1 Conv
fastmachinelearning/hls4ml pull request #366
Opened 2021-07-21 17:33 UTC by vloncar

As was discussed before, we currently don't support `Dense` layer being applied to `n`-dimensional tensor (with `n>1`, not counting the batch dimension). This operation is equivalent to doing 1x1 convolution over the same tensor, which we support as a special case. This PR does that by adding an optimizer that replaces `Dense` with `PointwiseConv1D/2D`. To support this, converter also had to be extended to properly handle the output shape as well as the `Dense` layer itself in the hls4ml IR.

Test case can be found [here](https://gist.github.com/vloncar/2b7bb326bb4b8878e6bb251612c8e670)

2021-07-21 17:38 UTC, vloncar commented
I should mention that the HLS implementation for 1x1 convolution for `io_parallel` is based on the `latency` implementations of Conv1D/2D. By no means are these the best possible implementations and we should explore better ways of doing this (like in the `dense_resource` function). But after this PR the changes to HLS will be localized to a single function in the`.h` files without touching the rest of the conversion flow.

2021-07-23 02:08 UTC, jmduarte approved these changes
Changes look good to me, and I tested it with the DeepMET and IN models I've been playing with

2021-07-26 17:34 UTC, jmduarte commented
Actually, I have a small fix related to #368: https://github.com/vloncar/hls4ml/pull/42

but perhaps we can discuss if this is the best way to do it.

2021-07-26 17:41 UTC, jmduarte requested changes

2021-07-26 17:41 UTC, jmduarte commented on hls4ml/model/optimizer/passes/multi_dense.py
> +        pw_node = model.make_node(class_name, node.name, pointwise_attrs, node.inputs.copy())
We somehow have to make sure the `pw_node` picks up the weights/biases from `node` (I'm not sure why it's not happening by default)

2021-08-04 19:04 UTC, vloncar commented
Do we need anything else before we merge this?

2021-08-04 23:47 UTC, jmduarte approved these changes

2021-08-04 23:48 UTC, merged