Add tracing support for the quartus backend
fastmachinelearning/hls4ml pull request #583
Opened 2022-06-24 23:11 UTC by jmitrevs

# Description

Tracing was only partially supported in the Quartus backend. This adds the missing features to enable support in the currently supported `io_parallel` style. (This will need to be expanded when streaming is added.)

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Tests

`test_trace.py` is added in pytest:  it is a simple copy of the `test_dense` with tracing enabled.

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/fastmachinelearning/hls4ml/blob/master/CONTRIBUTING.md).
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation -- not needed; should be identical as Vivado,
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.B# Description

2022-06-25 12:57 UTC, jmitrevs commented
I just made pr/583 locally with this pull request.

2022-07-21 16:22 UTC, jmitrevs commented
I think this is fairly straightforward and uncontroversial--mostly a copy of the Vivado behavior, updated for ac_fixed.  I would recommend reviewing it so we can merge it.

2022-07-22 11:08 UTC, bo3z requested changes
Looks good to me, happy to merge after removing the double declaration inside nnet_helpers.h

2022-07-22 11:16 UTC, jmitrevs commented on hls4ml/templates/quartus/firmware/nnet_utils/nnet_helpers.h
> +extern size_t trace_type_size;
You are right. I will remove them.

2022-07-22 11:18 UTC, bo3z commented
All good, happy to merge.

2022-07-22 11:37 UTC, merged